# Generated by Django 3.2.7 on 2021-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tender_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_Name', models.CharField(max_length=250)),
                ('Delivery_Date', models.CharField(max_length=250)),
                ('Unique_bid_number', models.CharField(max_length=250)),
                ('Unit_type', models.CharField(max_length=250)),
                ('Agent', models.CharField(max_length=250)),
                ('Related_Entity', models.CharField(max_length=250)),
                ('Volume_offered', models.IntegerField()),
                ('Volume_Accepted', models.IntegerField()),
                ('Delivery_Start', models.CharField(max_length=250)),
                ('Delivery_End', models.CharField(max_length=250)),
                ('Service_Duration', models.IntegerField()),
                ('Availability_Fee', models.IntegerField()),
                ('Total_Cost', models.IntegerField(blank=True, null=True)),
                ('RTM', models.CharField(max_length=250)),
                ('Accepted', models.CharField(max_length=250)),
                ('Rejection_code', models.IntegerField(blank=True, null=True)),
                ('Technology_Type', models.CharField(max_length=250)),
            ],
        ),
    ]
