# Generated by Django 3.2.7 on 2021-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210917_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_Name', models.CharField(max_length=250)),
                ('Delivery_Date', models.CharField(max_length=250)),
                ('Unique_bid_number', models.CharField(max_length=250)),
                ('Response_Unit', models.CharField(max_length=250)),
                ('Unit_type', models.CharField(max_length=250)),
                ('Agent_Or_Applicant', models.CharField(max_length=250)),
                ('Related_Entity', models.CharField(max_length=250)),
                ('Volume_offered', models.IntegerField()),
                ('Volume_Accepted', models.IntegerField()),
                ('Delivery_Start', models.CharField(max_length=250)),
                ('Delivery_End', models.CharField(max_length=250)),
                ('Service_Duration', models.IntegerField()),
                ('Availability_Fee', models.IntegerField()),
                ('Total_Cost', models.IntegerField(verbose_name=2)),
                ('RTM_Or_no_RTM', models.CharField(max_length=250)),
                ('Accepted_Or_Rejected', models.CharField(max_length=250)),
                ('Rejection_code', models.IntegerField(blank=True, null=True)),
                ('Technology_Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='tender_results',
        ),
    ]
